services:

  wireguard_server:
    image: lscr.io/linuxserver/wireguard
    container_name: wg_server
    ports:
      - 51820:51820/udp
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - WG_SERVER_ID=${WG_DEFAULT_SERVER_ID}
    volumes:
      - ./mnt/wg_config:/config
      - ./app/wg_customized/server.ini:/_tmp/cfg
      - ./app/wg_customized/entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    restart: unless-stopped
    networks:
      - proxy_net

  proxy:
    image: gogost/gost
    restart: always
    network_mode: service:wireguard_server
    environment:
      - GOST_LOGGER_LEVEL=warn
    command:
      - "-L=tcp://:8333/10.8.0.1:8333" # S3
      - "-L=tcp://:5432/10.8.0.1:5432" # DB
    depends_on:
      wireguard_server:
        condition: service_started

  redis_srv:
    image: redis
    restart: always
    # expose Redis port only for testing!
    #ports:
    #  - 6379:6379
    volumes:
      - ./mnt/redis_dump:/data
    command: >
      redis-server
      --maxmemory ${REDIS_MAX_MEMORY:-128mb}
      --maxmemory-policy noeviction
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - proxy_net

  jfs_format:
    image: juicedata/mount
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        if juicefs status redis://redis_srv:6379/1; then
          echo '✅ JuiceFS already initialized (skipping format).'
        else
          juicefs format \
            --storage s3 \
            --bucket http://wireguard_server:8333/jfs-bucket-2 \
            --access-key any --secret-key any \
            --capacity ${JFS_CAPACITY_GB} \
            redis://redis_srv:6379/1 \
            ${JFS_NAME}
        fi
    depends_on:
      redis_srv:
        condition: service_healthy
      proxy:
        condition: service_started
    networks:
      - proxy_net

  jfs_mount:
    image: juicedata/mount
    restart: always
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    security_opt:
      - apparmor:unconfined
    volumes:
      - ./mnt/jfs_cache:/var/jfs_cache
      - ./mnt/jfs:/mnt/jfs:shared
    command: >
      juicefs mount
      --cache-dir /var/jfs_cache
      --buffer-size ${JFS_BUFFER_SIZE_MB}
      --cache-size ${JFS_CACHE_SIZE_MB}
      --free-space-ratio 0.1
      --get-timeout 10
      --put-timeout 10
      --io-retries 2
      redis://redis_srv:6379/1
      /mnt/jfs
    depends_on:
      jfs_format:
        condition: service_completed_successfully
      proxy:
        condition: service_started
    networks:
      - proxy_net

  web_browser:
    image: lscr.io/linuxserver/chromium:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CHROME_CLI=--remote-debugging-port=9222 --remote-allow-origins=* https://www.google.com/
      - HARDEN_DESKTOP=true
      - HARDEN_OPENBOX=true
      - SELKIES_UI_SHOW_SIDEBAR=false
    volumes:
      - ./mnt/web_browser:/config
      - ./app/browser/openbox/:/config/.config/openbox
    ports:
      - 9222:9223 # devtools port, TEST ONLY!
      - 3001:3001 # https port, TEST ONLY!
    shm_size: "1gb"
    networks:
      - sandbox_net

  devtool_proxy:
    image: gogost/gost
    network_mode: service:web_browser
    command: -L tcp://:9223/127.0.0.1:9222
    depends_on:
      - web_browser

networks:
  proxy_net:
    driver: overlay
    attachable: true

  sandbox_net:
    driver: bridge
