services:

  gateway:
    image: gateway:latest
    build:
      context: ./app/gateway
      dockerfile: Dockerfile
    environment:
      - REDIRECT_URL=/auth-test/login
      - REDIRECT_URL_ARGKEY=next
      - DEFAULT_REQ_RATE=$GATEWAY_DEFAULT_REQ_RATE
      - DEFAULT_BURST=$GATEWAY_DEFAULT_BURST
      - DEFAULT_CONN_MAX=$GATEWAY_DEFAULT_CONN_MAX
      - JWT_COOKIE_NAME=jwt_token # ngx.var.cookie_* must be lower-case and no-hyphen
      - JWT_SECRET_URL=auth:19721/secret
      - DOMAIN=$GATEWAY_DOMAIN
    ports:
      - target: 443
        published: 80
        mode: host # to pass in REAL IP
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gateway_net
    entrypoint: ["./entrypoint.sh", "$DOMAIN"]

  echo1:
    image: approach0/echo-httpd
    networks:
      - gateway_net
    command: "node hello.js echo1"
    deploy:
      labels:
        gateway.route: foo
        gateway.port: 8080
        gateway.limits: '{"rate": 10, "burst": 10, "conn": 1}'

  echo2:
    image: approach0/echo-httpd
    networks:
      - gateway_net
    command: "node hello.js echo2"
    deploy:
      labels:
        gateway.route: bar
        gateway.port: 8080
        gateway.limits: '{"rate": 1, "burst": 0, "conn": 10}'

  echo3:
    image: approach0/echo-httpd
    networks:
      - gateway_net
    command: "node hello.js echo3"
    deploy:
      labels:
        gateway.route: baz
        gateway.port: 8080
        gateway.protect: /protected,/private

  auth:
    image: auth:latest
    build:
      context: ./app/auth
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DB_URL=postgresql://${DB_USER}:${DB_PASS}@wireguard_server:5432/backend_db
      - LOGIN_MAX_ATTEMPTS=10
      - JWT_EXPIRE_DAYS=5
      - JWT_COOKIE_NAME=JWT_Token
      - REDIRECT_URL=/login
      - REDIRECT_URL_ARGKEY=next
      - OAUTH2_PROVIDERS=google,github
      - OAUTH2_CALLBK_PREFIX=https://__REQ_DOMAIN__/auth
      - OAUTH2_GOOGLE_CLIENT_ID=${OAUTH2_GOOGLE_CLIENT_ID}
      - OAUTH2_GOOGLE_CLIENT_SECRET=${OAUTH2_GOOGLE_CLIENT_SECRET}
      - OAUTH2_GITHUB_CLIENT_ID=${OAUTH2_GITHUB_CLIENT_ID}
      - OAUTH2_GITHUB_CLIENT_SECRET=${OAUTH2_GITHUB_CLIENT_SECRET}
      - EMAIL_SMTP_KEY=${EMAIL_SMTP_KEY}
      - EMAIL_DOMAIN=${EMAIL_DOMAIN}
    deploy:
      labels:
        gateway.route: auth
        gateway.port: 19721
        gateway.limits: '{"rate": 1, "burst": 10, "conn": 10}'
        gateway.internal: /secret
    networks:
      - gateway_net
      - proxy_net

  auth_test:
    image: auth:latest
    build:
      context: ./app/auth
      dockerfile: Dockerfile
    command: ["node", "test/server.js"]
    environment:
      - JWT_SECRET_URL=auth:19721/secret
      - JWT_COOKIE_NAME=JWT_Token
      - AUTH_BASE_URL=/auth
      - REDIRECT_URL=/auth-test/login
      - REDIRECT_URL_ARGKEY=next
    deploy:
      labels:
        gateway.route: auth-test
        gateway.port: 3000
    networks:
      - gateway_net

  ui_login:
    image: ui_login:latest
    build:
      context: ./app/ui_login
      dockerfile: Dockerfile
      args:
        - AUTH_BASE_URL=/auth
        - UI_BASE=/u
        - REDIRECT_URL_ARGKEY=next
    deploy:
      labels:
        gateway.route: u
        gateway.port: 8080
    networks:
      - gateway_net

  ui_404:
    image: ui_404:latest
    build:
      context: ./app/ui_404
      dockerfile: Dockerfile
      args:
        - REDIRECT_URL=/
        - REDIRECT_TIMEOUT=10
    deploy:
      labels:
        gateway.route: _404_
        gateway.port: 8080
    networks:
      - gateway_net

networks:
  gateway_net:
    driver: overlay
    attachable: true

  proxy_net:
    external: true
    name: sandbox_user_0_proxy_net
