services:

  gateway:
    image: gateway:latest
    build:
      context: ./app/gateway
      dockerfile: Dockerfile
    ports:
      - target: 443
        published: 80
        mode: host # to pass in REAL IP
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gateway_net

  echo1:
    image: approach0/echo-httpd
    networks:
      - gateway_net
    command: "node hello.js echo8921"
    deploy:
      labels:
        gateway.route: foo
        gateway.port: 8080
        gateway.limits: '{"rate": 10, "burst": 10, "conn": 1}'

  echo2:
    image: approach0/echo-httpd
    networks:
      - gateway_net
    command: "node hello.js echo8922"
    deploy:
      labels:
        gateway.route: bar
        gateway.port: 8080
        gateway.limits: '{"rate": 1, "conn": 10}'

networks:
  gateway_net:
    driver: overlay
    attachable: true
