# The proxy_set_header directives are inherited from the previous level if and
# only if there are no proxy_set_header directives defined on the current level.
# Ref: http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_set_header

# --- WebSocket ---
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "Upgrade";
# --- pass IP and protocol ---
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Original-URI $request_uri;
# --- misc. ---
proxy_cache off;
proxy_redirect off;
proxy_buffering off;
client_max_body_size 5M;
