# The proxy_set_header directives are inherited from the previous level if and
# only if there are no proxy_set_header directives defined on the current level.
# Ref: http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_set_header

proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Original-URI $request_uri;
proxy_cache off;
proxy_redirect off;
